// SMPTE-RA Class 13/14 organization registry
// Source: https://www.smpte-ra.org/class-1314-registrations
// Key: bytes 8-9 of the normalized UL (0-indexed), e.g. "0d01"
window.ORG_REGISTRY = {
  '0d00': { name: 'Public Use (generic)',            cls: 13 },
  '0d01': { name: 'AAF Association',                 cls: 13 },
  '0d02': { name: 'EBU/UER',                         cls: 13 },
  '0d03': { name: 'Pro-MPEG Forum',                  cls: 13 },
  '0d04': { name: 'BBC',                             cls: 13 },
  '0d05': { name: 'IRT',                             cls: 13 },
  '0d06': { name: 'ARIB',                            cls: 13 },
  '0d07': { name: 'AMIA',                            cls: 13 },
  '0d08': { name: 'PBS',                             cls: 13 },
  '0d09': { name: 'ASC',                             cls: 13 },
  '0d0a': { name: 'AES',                             cls: 13 },
  '0d0b': { name: 'Dutch Guild',                     cls: 13 },
  '0d0c': { name: 'DPP',                             cls: 13 },
  '0d0d': { name: 'Ad-ID',                           cls: 13 },
  '0d0e': { name: 'LoC',                             cls: 13 },
  '0d0f': { name: 'ISDCF',                           cls: 13 },
  '0e00': { name: 'Private Use (generic)',            cls: 14 },
  '0e01': { name: 'MISB Systems',                    cls: 14 },
  '0e02': { name: 'ASPA',                            cls: 14 },
  '0e03': { name: 'MISB Classified',                 cls: 14 },
  '0e04': { name: 'Avid Technology Inc.',            cls: 14 },
  '0e05': { name: 'CNN',                             cls: 14 },
  '0e06': { name: 'Sony Corporation',                cls: 14 },
  '0e07': { name: 'IdeasUnlimited.TV',               cls: 14 },
  '0e08': { name: 'IPV Ltd',                         cls: 14 },
  '0e09': { name: 'Dolby Laboratories Inc.',         cls: 14 },
  '0e0a': { name: 'Snell & Wilcox',                  cls: 14 },
  '0e0b': { name: 'Omneon Video Networks',           cls: 14 },
  '0e0c': { name: 'Ascent Media Group Inc.',         cls: 14 },
  '0e0d': { name: 'Quantel Ltd',                     cls: 14 },
  '0e0e': { name: 'Panasonic',                       cls: 14 },
  '0e0f': { name: 'Grass Valley Inc.',               cls: 14 },
  '0e10': { name: 'Doremi Labs Inc.',                cls: 14 },
  '0e11': { name: 'EVS Broadcast Equipment',         cls: 14 },
  '0e12': { name: 'Turner Broadcasting System Inc.', cls: 14 },
  '0e13': { name: 'NL Technology LLC',               cls: 14 },
  '0e14': { name: 'Harris Corporation',              cls: 14 },
  '0e15': { name: 'Canon Inc.',                      cls: 14 },
  '0e16': { name: 'D-BOX Technologies',              cls: 14 },
  '0e17': { name: 'ARRI',                            cls: 14 },
  '0e18': { name: 'JVC',                             cls: 14 },
  '0e19': { name: '3ality Technica',                 cls: 14 },
  '0e1a': { name: 'NHK',                             cls: 14 },
  '0e1b': { name: 'HBO',                             cls: 14 },
  '0e1d': { name: 'DTS Inc.',                        cls: 14 },
  '0e1e': { name: 'FLIR Systems Inc.',               cls: 14 },
  '0e1f': { name: 'Barco',                           cls: 14 },
  '0e20': { name: 'Apple Inc.',                      cls: 14 },
  '0e21': { name: 'Fraunhofer IIS',                  cls: 14 },
  '0e22': { name: 'RED',                             cls: 14 },
  '0e23': { name: 'CRIFST',                          cls: 14 },
  '0e24': { name: 'FUJIFILM',                        cls: 14 },
};
